sudo: required
services:
  - docker

before_install:
  - docker build -t alextagger/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alextagger/docker-react npm run test

language: generic

# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "docker-react-alextagger"
#   env: "docker-react-alextagger-env"
#   bucket-name: "AWS_BUCKET_NAME"
#   bucket-path: "docker-react-alextagger"
#   on:
#     branch: master

# access_key_id:
#   secure: "$AWS_ACCESS_KEY"
# secret_access_key:
#   secure: "$AWS_SECRET_KEY"