sudo: required
services:
  - docker

before_install:
  - docker build -t alextagger/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alextagger/docker-react npm run test

language: generic